### ISSUE TITLE
gpio-config.json

### ISSUE THREAD

**Issue by danpcl** [kevinherron/pi-server#2]
Hi Kevin, 

When I modified the gpio configuration in the "gpio-config.json.example" and saved as "gpio-config.json" 
I started the opc-ua server, the server can't not be connected by UAExpert.

Can you teach me how to solve this problem?

Thx.

**Comment by kevinherron** [comment]
Were you able to connect before you modified it? Were there any errors in the log file?

**Comment by danpcl** [comment]
I could connect before I modified it.

the error code like below:

INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at com.digitalpetri.opcua.sdk.server.NamespaceManager.registerAndAdd(NamespaceManager.java:90)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at com.digitalpetri.opcua.raspberrypi.PiServer.<init>(PiServer.java:90)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at com.digitalpetri.opcua.raspberrypi.PiServer.main(PiServer.java:52)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:483)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:744)
STATUS | wrapper  | 2016/06/22 20:48:07 | <-- Wrapper Stopped
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at com.digitalpetri.opcua.sdk.server.NamespaceManager.registerAndAdd(NamespaceManager.java:90)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at com.digitalpetri.opcua.raspberrypi.PiServer.<init>(PiServer.java:90)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at com.digitalpetri.opcua.raspberrypi.PiServer.main(PiServer.java:52)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:483)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/06/22 20:48:04 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:744)
STATUS | wrapper  | 2016/06/22 20:48:07 | <-- Wrapper Stopped

Sorry, I am a rookie in opc-ua.

**Comment by kevinherron** [comment]
Is there somewhere you can upload the whole file? I think there may be an error parsing the GPIO config, which is causing the rest of the server startup to fail.

**Comment by danpcl** [comment]
Actually, I just save the "gpio-config.json.example" as "gpio-config.json".
I have not modified the content.
